version: 2
jobs:
  deployDev:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "dc:fb:3e:17:32:51:3b:50:de:a0:81:22:58:79:e6:3e"
      - run: 
          name: Deploy To VPS
          command: |
            ssh-keyscan $SSH_HOST >> ~/.ssh/config
            ssh $SSH_USER@$SSH_HOST "cd ./zooProd; git checkout develop; git pull; yarn; yarn build:api; yarn build:frontend; echo hi"
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo test
workflows:
  version: 2
  testAndDeployDev:
    jobs:
      - test:
      - deployDev:
          requires:
            - test
          filters:
            branches:
              only: develop