version: 2
jobs:
  deployDev:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b7:7f:69:26:cd:94:67:ad:2c:c2:14:02:4d:02:74:38"
      - run:
          name: Populate known hosts
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy To VPS
          command: ssh $SSH_USER@$SSH_HOST "cd ./zooProd; git fetch --all; git reset --hard origin/develop; chmod 700 ./deploy.sh; ./deploy.sh;"
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: 
          name: Eslint
          command: yarn test:eslint
      - run:
          name: Unit Tests
          command: yarn test

workflows:
  version: 2
  testAndDeployDev:
    jobs:
      - test
      - deployDev:
          requires:
            - test
          filters:
            branches:
              only: develop