version: 2
jobs:
  deployDev:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "dc:fb:3e:17:32:51:3b:50:de:a0:81:22:58:79:e6:3e"
      - run:
          name: Populate known hosts
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy To VPS
          command: ssh $SSH_USER@$SSH_HOST "cd ./zooProd; git checkout develop; git pull; chmod 700 ./deploy.sh; ./deploy.sh;"
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo test
workflows:
  version: 2
  testAndDeployDev:
    jobs:
      - test
      - deployDev:
          requires:
            - test
          filters:
            branches:
              only: develop