version: 2
jobs:
  deployDev:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - add_ssh_keys
      - run: 
          name: Deploy To VPS
          command: ssh $SSH_USER@$SSH_HOST "cd ./zooProd; git checkout develop; git pull; npm install; npm run build:api; npm run build:frontend; pm2 start;"
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo test
workflows:
  version: 2
  testandDeployToDev:
    jobs:
      - test
      - deployDev